version: "3.9"
services:
  #container 3
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: courses_mcsv_pro6_kubernates_11
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  #container 4
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mcsv_project6_cours
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  #container 1
  users-mcsv-container:
    container_name: users-mcsv-container
    #image: mcsv-users
    #we construct the image from the Dockerfile
    build:
      context: ./
      dockerfile: ./mcsv-users/Dockerfile
    ports:
      - "8081:8081"
    env_file: .\mcsv-users\.env
    networks:
        - spring
    #this container depends on mysql8
    depends_on:
        - mysql8
    restart: always
  #container 2
  cours-mcsv-container:
    container_name: cours-mcsv-container
    #image: mcsv-cours
    #we construct the image from the Dockerfile
    build:
      context: ./
      dockerfile: ./mcsv-cours/Dockerfile
    ports:
      - "8082:8082"
    env_file: .\mcsv-cours\.env
    networks:
      - spring
    #this container depends on postgres14
    depends_on:
      - postgres14
      - users-mcsv-container
    restart: always
#define volumes
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

#define networks
networks:
  spring:
    external: true




