version: "3.9"
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mcsv_project6_cours
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  #container 2
  cours-mcsv-container:
    container_name: cours-mcsv-container
    image: daniella03/cours-mcsv
    #we construct the image from the Dockerfile
    #build:
     # context: ./
      #dockerfile: ./mcsv-cours/Dockerfile
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      DB_HOST: postgres14:5432
      DB_DATABASE: mcsv_project6_cours
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USERS_URL: ec2-18-205-246-26.compute-1.amazonaws.com:8081
    networks:
      - spring
    #this container depends on postgres14
    depends_on:
      - postgres14
      - users-mcsv-container
    restart: always
#define volumes
volumes:
  data-postgres:
    name: data-postgres

#define networks
networks:
  spring:
    name: spring





